version: "3.9"
services:
  main:
    build: .
    command: ["air"]
    ports:
      - 9090:9090
    environment:
      ADDR: :9090
    volumes:
      - .:/app
    networks:
      - go-users-ms

networks:
  go-users-ms:
