version: "3.9"
services:
  main:
    build: .
    command: ["air"]
    container_name: users-ms
    environment:
      ADDR: :9090
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_NAME: datastore
      DB_PROD: db-prod
      DB_TEST: db-test
    volumes:
      - .:/app
    networks:
      - users
    depends_on:
      - db-prod

  db-prod:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datastore
    volumes:
      - .dbdata:/var/lib/postgresql/datastore
    networks:
      - users

  db-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datastore
    networks:
      - users

networks:
  users:
    name: users_net
